import { Button } from "../../components";
import { Input } from "../../components";

const TableExcel = () => {
  return (
    <div className="tableEx_page">
        <div className="tableEx_page_container">

            <table>
                <thead className="tableEx_page_container_thead">
                <tr>
                    <th>شماره فاکتور</th>
                    <th>تاریخ</th>
                    <th>متن یک</th>
                    <th>متن دوم</th>
                    <th>متن سوم</th>
                    <th>متن چهرم</th>
                    <th>متن پنجم</th>
                </tr>
                </thead>
                <tbody className="tableEx_page_container_tbody">
                <tr>
                    <td>cell1_1</td>
                    <td>cell2_1</td>
                    <td>cell3_1</td>
                    <td>cell4_1</td>
                    <td>cell5_1</td>
                    <td>cell6_1</td>
                    <td>cell7_1</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_2</td>
                    <td>cell2_2</td>
                    <td>cell3_2</td>
                    <td>cell4_2</td>
                    <td>cell5_2</td>
                    <td>cell6_2</td>
                    <td>cell7_2</td>
                </tr>
                <tr>
                    <td>cell1_3</td>
                    <td>cell2_3</td>
                    <td>cell3_3</td>
                    <td>cell4_3</td>
                    <td>cell5_3</td>
                    <td>cell6_3</td>
                    <td>cell7_3</td>
                </tr>
                <tr>
                    <td>cell1_4</td>
                    <td>cell2_4</td>
                    <td>cell3_4</td>
                    <td>cell4_4</td>
                    <td>cell5_4</td>
                    <td>cell6_4</td>
                    <td>cell7_4</td>
                </tr>
                <tr>
                    <td>cell1_5</td>
                    <td>cell2_5</td>
                    <td>cell3_5</td>
                    <td>cell4_5</td>
                    <td>cell5_5</td>
                    <td>cell6_5</td>
                    <td>cell7_5</td>
                </tr>
                <tr>
                    <td>cell1_6</td>
                    <td>cell2_6</td>
                    <td>cell3_6</td>
                    <td>cell4_6</td>
                    <td>cell5_6</td>
                    <td>cell6_6</td>
                    <td>cell7_6</td>
                </tr>
                <tr>
                    <td>cell1_7</td>
                    <td>cell2_7</td>
                    <td>cell3_7</td>
                    <td>cell4_7</td>
                    <td>cell5_7</td>
                    <td>cell6_7</td>
                    <td>cell7_7</td>
                </tr>
                <tr>
                    <td>cell1_8</td>
                    <td>cell2_8</td>
                    <td>cell3_8</td>
                    <td>cell4_8</td>
                    <td>cell5_8</td>
                    <td>cell6_8</td>
                    <td>cell7_8</td>
                </tr>
                <tr>
                    <td>cell1_9</td>
                    <td>cell2_9</td>
                    <td>cell3_9</td>
                    <td>cell4_9</td>
                    <td>cell5_9</td>
                    <td>cell6_9</td>
                    <td>cell7_9</td>
                </tr>
                </tbody>
                <tfoot className="tableEx_page_container_tfoot">
                <tr>
                    <td>foot1</td>
                    <td>foot2</td>
                    <td>foot3</td>
                    <td>foot4</td>
                    <td>foot5</td>
                    <td>foot6</td>
                    <td>foot7</td>
                </tr>
                </tfoot>
            </table>

        </div>

        <div className="tableEx_page_btn">
            <div>  
            <Button text={"بازگشت"} size={"normal"} type={"light"}/>
                </div> 
            <div className="tableEx_page_btn--left">
            <Button text={"دانلود صورت حساب"} size={"large"} type={"light"}/>
            <Button text={"تایید"} size={"normal"} type={"light"}/>
            </div>
        </div>
    </div>
  );
};

export default TableExcel;
